name: Scheduled Deploy
on:
  schedule:
    # * is a special character in YAML so you have to quote this string.
    # See https://crontab.guru/#0_7_*_*_*
    - cron:  '0 7 * * *'

jobs:
  Deploy:
    name: Deploying netlify through build hook
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.URL }}
      METHOD: POST
    steps:
      - id: ping
        uses: jonathan-s/pinger@master
